# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ryanfiller.com
email: ryanfiller89@gmail.com
description: porftfolio and blog for ryan filler
url: "http://ryanfiller.com" # the base hostname & protocol for your site, e.g. http://example.com
author: ryanfiller_
twitter_username: ryanfiller_
github_username:  ryanfiller89
facebook:
  admins: 1289580190
logo: /assets/images/site-assets/ryanfiller.jpg
social:
  name: Ryan Filler
  links:
    - https://twitter.com/ryanfiller_
    - https://www.facebook.com/ryan.filler
    - https://www.linkedin.com/in/ryanfiller
    - https://plus.google.com/u/0/112417000136872017947
    - https://github.com/ryanfiller89

portfolio-layout: gifs

# Build settings
markdown: kramdown

permalink: /blog/:title/

pagination:
  collection: posts
  limit: false
  per_page: 10
  permalink: /page:num/
  title_suffix: ""

defaults:
    -
        scope:
            type: "posts"
        values:
            parent: blog
    -
        scope:
            type: "portfolio"
        values:
            parent: portfolio

collections:
    portfolio:
        output: true
        permalink: /portfolio/:title/

sass:
    sass_dir: /assets/_scss

gems:
  - jekyll-feed
  - octopress-paginate
  - octopress-autoprefixer
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
